services:
  teddycloud:
    container_name: teddycloud
    hostname: teddycloud
    image: ghcr.io/toniebox-reverse-engineering/teddycloud:tc_v0.7.0_alpine@sha256:d001c4124fbf04f274fa176c294fa8a1cbdc96bd4b70a82b2f1470a43def3763
    # ports:
    #  - 80:80 #optional (for the webinterface)
    #  - 8443:8443 #optional (for the webinterface)
    #  - 443:443 #Port is needed for the connection for the box, must not be changed!
    volumes:
      - certs:/teddycloud/certs
      - config:/teddycloud/config
      - content:/teddycloud/data/content
      - library:/teddycloud/data/library
      - firmware:/teddycloud/data/firmware
      - cache:/teddycloud/data/cache
    restart: unless-stopped
  teddycloud2:
    image: ghcr.io/toniebox-reverse-engineering/teddycloud:tc_v0.7.0@sha256:30e74ee78070daa9434e1d756e1be6d149a126dbe61493e720064907fb78aa7d
volumes:
  certs:
  config:
  content:
  library:
  firmware:
  cache: