services:
  teddycloud:
    container_name: teddycloud
    hostname: teddycloud
    image: ghcr.io/toniebox-reverse-engineering/teddycloud:tc_v0.6.2_alpine@sha256:3ae9363cb5f750752803e20e322255e3f4849fa049bb04dc4865160a978284f5
    # ports:
    #  - 80:80 #optional (for the webinterface)
    #  - 8443:8443 #optional (for the webinterface)
    #  - 443:443 #Port is needed for the connection for the box, must not be changed!
    volumes:
      - certs:/teddycloud/certs
      - config:/teddycloud/config
      - content:/teddycloud/data/content
      - library:/teddycloud/data/library
      - firmware:/teddycloud/data/firmware
      - cache:/teddycloud/data/cache
    restart: unless-stopped
  teddycloud2:
    image: ghcr.io/toniebox-reverse-engineering/teddycloud:tc_v0.6.2@sha256:776b42c40728c6d3251d502031d7c1852eef578bed424a2ea662edf1da952e48
volumes:
  certs:
  config:
  content:
  library:
  firmware:
  cache: